<?php

namespace Database\Seeders;

use App\Models\Organization;
use Illuminate\Database\Seeder;

class OrganizationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $organizations = [
            [
                'name' => 'Dewan Pimpinan Pusat',
                'type' => 'dpp',
                'city' => 'Samarinda',
                'address' => 'Jl. Perikanan No. 1, Samarinda',
                'phone' => '0541-123456',
                'email' => 'dpp@fisheries.com',
                'chairman' => 'Dr. H. Ahmad Sudirman',
                'secretary' => 'Siti Rahayu',
                'treasurer' => 'Budi Santoso',
                'established_year' => 2010,
                'member_count' => 150,
                'description' => 'Dewan Pimpinan Pusat FISHERIES Indonesia',
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'DPC Samarinda',
                'type' => 'dpc',
                'city' => 'Samarinda',
                'address' => 'Jl. Sudirman No. 45, Samarinda',
                'phone' => '0541-234567',
                'email' => 'samarinda@fisheries.com',
                'chairman' => 'H. Budi Santoso',
                'secretary' => 'Ahmad Fauzi',
                'treasurer' => 'Dewi Kusuma',
                'established_year' => 2012,
                'member_count' => 45,
                'description' => 'DPC Samarinda - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'DPC Balikpapan',
                'type' => 'dpc',
                'city' => 'Balikpapan',
                'address' => 'Jl. Soekarno Hatta No. 78, Balikpapan',
                'phone' => '0542-345678',
                'email' => 'balikpapan@fisheries.com',
                'chairman' => 'H. Candra Wijaya',
                'secretary' => 'Rini Susanti',
                'treasurer' => 'Agus Pratama',
                'established_year' => 2013,
                'member_count' => 38,
                'description' => 'DPC Balikpapan - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'DPC Bontang',
                'type' => 'dpc',
                'city' => 'Bontang',
                'address' => 'Jl. MT Haryono No. 23, Bontang',
                'phone' => '0548-456789',
                'email' => 'bontang@fisheries.com',
                'chairman' => 'H. Dedi Kurniawan',
                'secretary' => 'Maya Sari',
                'treasurer' => 'Rudi Hartono',
                'established_year' => 2014,
                'member_count' => 25,
                'description' => 'DPC Bontang - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'DPC Berau',
                'type' => 'dpc',
                'city' => 'Berau',
                'address' => 'Jl. Ahmad Yani No. 15, Tanjung Redeb',
                'phone' => '0554-23456',
                'email' => 'berau@fisheries.com',
                'chairman' => 'H. Eko Prasetyo',
                'secretary' => 'Nina Wulandari',
                'treasurer' => 'Hendra Gunawan',
                'established_year' => 2015,
                'member_count' => 20,
                'description' => 'DPC Berau - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'DPC Kutai Kartanegara',
                'type' => 'dpc',
                'city' => 'Kutai Kartanegara',
                'address' => 'Jl. Diponegoro No. 88, Tenggarong',
                'phone' => '0541-345678',
                'email' => 'kukar@fisheries.com',
                'chairman' => 'H. Faisal Rahman',
                'secretary' => 'Diana Putri',
                'treasurer' => 'Bambang Sutrisno',
                'established_year' => 2015,
                'member_count' => 30,
                'description' => 'DPC Kutai Kartanegara - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'DPC Paser',
                'type' => 'dpc',
                'city' => 'Paser',
                'address' => 'Jl. Proklamasi No. 12, Tanah Grogot',
                'phone' => '0543-45678',
                'email' => 'paser@fisheries.com',
                'chairman' => 'H. Gunawan Wibowo',
                'secretary' => 'Rina Susanti',
                'treasurer' => 'Ahmad Fauzi',
                'established_year' => 2016,
                'member_count' => 18,
                'description' => 'DPC Paser - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'DPC Penajam Paser Utara',
                'type' => 'dpc',
                'city' => 'Penajam Paser Utara',
                'address' => 'Jl. Sudirman No. 25, Penajam',
                'phone' => '0542-56789',
                'email' => 'penajam@fisheries.com',
                'chairman' => 'H. Hendra Wijaya',
                'secretary' => 'Siti Aminah',
                'treasurer' => 'Dedi Kurniawan',
                'established_year' => 2016,
                'member_count' => 15,
                'description' => 'DPC Penajam Paser Utara - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 8,
            ],
            [
                'name' => 'DPC Kutai Barat',
                'type' => 'dpc',
                'city' => 'Kutai Barat',
                'address' => 'Jl. Merdeka No. 33, Sendawar',
                'phone' => '0545-67890',
                'email' => 'kubar@fisheries.com',
                'chairman' => 'H. Irfan Hakim',
                'secretary' => 'Maya Sari',
                'treasurer' => 'Eko Prasetyo',
                'established_year' => 2017,
                'member_count' => 12,
                'description' => 'DPC Kutai Barat - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 9,
            ],
            [
                'name' => 'DPC Kutai Timur',
                'type' => 'dpc',
                'city' => 'Kutai Timur',
                'address' => 'Jl. Ahmad Yani No. 77, Sangatta',
                'phone' => '0553-78901',
                'email' => 'kutim@fisheries.com',
                'chairman' => 'H. Joko Santoso',
                'secretary' => 'Nina Wulandari',
                'treasurer' => 'Faisal Rahman',
                'established_year' => 2017,
                'member_count' => 22,
                'description' => 'DPC Kutai Timur - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 10,
            ],
            [
                'name' => 'DPC Mahakam Ulu',
                'type' => 'dpc',
                'city' => 'Mahakam Ulu',
                'address' => 'Jl. Pembangunan No. 5, Ujoh Bilang',
                'phone' => '0554-89012',
                'email' => 'mahulu@fisheries.com',
                'chairman' => 'H. Kurniawan Dedi',
                'secretary' => 'Diana Putri',
                'treasurer' => 'Gunawan Wibowo',
                'established_year' => 2018,
                'member_count' => 10,
                'description' => 'DPC Mahakam Ulu - Komunitas Perikanan',
                'is_active' => true,
                'display_order' => 11,
            ],
        ];


        foreach ($organizations as $organization) {
            Organization::create($organization);
        }
    }
}
