<?php

return [
    'Aceh' => ['Banda Aceh', 'Langsa', 'Lhokseumawe', 'Sabang', 'Subulussalam', 'Kabupaten Aceh Besar', 'Kabupaten Pidie'],
    'Sumatera Utara' => ['Medan', 'Binjai', 'Pematangsiantar', 'Tanjungbalai', 'Tebing Tinggi', 'Padang Sidempuan', 'Sibolga', 'Gunungsitoli'],
    'Sumatera Barat' => ['Padang', 'Bukittinggi', 'Payakumbuh', 'Solok', 'Sawahlunto', 'Padang Panjang', 'Pariaman'],
    'Riau' => ['Pekanbaru', 'Dumai'],
    'Jambi' => ['Jambi', 'Sungai Penuh'],
    'Sumatera Selatan' => ['Palembang', 'Lubuklinggau', 'Prabumulih', 'Pagar Alam'],
    'Bengkulu' => ['Bengkulu'],
    'Lampung' => ['Bandar Lampung', 'Metro'],
    'Kepulauan Bangka Belitung' => ['Pangkal Pinang'],
    'Kepulauan Riau' => ['Batam', 'Tanjung Pinang'],
    'DKI Jakarta' => ['Jakarta Pusat', 'Jakarta Utara', 'Jakarta Barat', 'Jakarta Selatan', 'Jakarta Timur', 'Kepulauan Seribu'],
    'Jawa Barat' => ['Bandung', 'Bekasi', 'Bogor', 'Depok', 'Cimahi', 'Cirebon', 'Sukabumi', 'Tasikmalaya', 'Banjar', 'Kabupaten Bogor'],
    'Jawa Tengah' => ['Semarang', 'Surakarta', 'Magelang', 'Pekalongan', 'Salatiga', 'Tegal', 'Kabupaten Banyumas'],
    'DI Yogyakarta' => ['Yogyakarta', 'Sleman', 'Bantul', 'Gunungkidul', 'Kulon Progo'],
    'Jawa Timur' => ['Surabaya', 'Malang', 'Batu', 'Madiun', 'Kediri', 'Blitar', 'Pasuruan', 'Probolinggo', 'Mojokerto', 'Kabupaten Sidoarjo'],
    'Banten' => ['Tangerang', 'Tangerang Selatan', 'Serang', 'Cilegon'],
    'Bali' => ['Denpasar', 'Badung', 'Gianyar', 'Buleleng', 'Tabanan', 'Karangasem', 'Klungkung', 'Bangli', 'Jembrana'],
    'Nusa Tenggara Barat' => ['Mataram', 'Bima', 'Sumbawa'],
    'Nusa Tenggara Timur' => ['Kupang', 'Manggarai', 'Sikka'],
    'Kalimantan Barat' => ['Pontianak', 'Singkawang'],
    'Kalimantan Tengah' => ['Palangka Raya', 'Kotawaringin Barat', 'Kotawaringin Timur'],
    'Kalimantan Selatan' => ['Banjarmasin', 'Banjarbaru', 'Banjar'],
    'Kalimantan Timur' => ['Samarinda', 'Balikpapan', 'Bontang', 'Kutai Kartanegara', 'Berau', 'Kutai Barat', 'Kutai Timur', 'Mahakam Ulu', 'Paser', 'Penajam Paser Utara'],
    'Kalimantan Utara' => ['Tarakan', 'Bulungan', 'Malinau', 'Nunukan', 'Tana Tidung'],
    'Sulawesi Utara' => ['Manado', 'Bitung', 'Tomohon', 'Kotamobagu', 'Minahasa'],
    'Sulawesi Tengah' => ['Palu', 'Poso', 'Donggala'],
    'Sulawesi Selatan' => ['Makassar', 'Parepare', 'Palopo', 'Bone', 'Gowa', 'Toraja'],
    'Sulawesi Tenggara' => ['Kendari', 'Baubau', 'Wakatobi'],
    'Gorontalo' => ['Gorontalo', 'Kabupaten Gorontalo'],
    'Sulawesi Barat' => ['Mamuju', 'Majene', 'Polewali Mandar'],
    'Maluku' => ['Ambon', 'Tual'],
    'Maluku Utara' => ['Ternate', 'Tidore Kepulauan'],
    'Papua' => ['Jayapura', 'Kabupaten Jayapura', 'Biak Numfor'],
    'Papua Barat' => ['Manokwari', 'Fakfak'],
    'Papua Selatan' => ['Merauke', 'Boven Digoel', 'Asmat', 'Mappi'],
    'Papua Tengah' => ['Nabire', 'Mimika', 'Puncak Jaya', 'Paniai'],
    'Papua Pegunungan' => ['Jayawijaya', 'Lanny Jaya', 'Tolikara', 'Yahukimo'],
    'Papua Barat Daya' => ['Sorong', 'Sorong Selatan', 'Raja Ampat'],
];
